import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  Building2,
  User,
  Users,
  MapPin,
  FileStack,
  Hash,
  Home,
  Ruler,
  CheckCircle2,
  Clock,
  PieChart,
  Hammer,
  ShieldAlert,
  CloudRain,
  FileWarning,
  Folder,
  Camera,
  Activity,
  AlertCircle,
  DollarSign,
  Eye,
  Edit,
  Trash2,
} from 'lucide-angular';

@NgModule({
  imports: [
    LucideAngularModule.pick({
      Building2,
      User,
      Users,
      MapPin,
      FileStack,
      Hash,
      Home,
      Ruler,
      CheckCircle2,
      Clock,
      PieChart,
      Hammer,
      ShieldAlert,
      CloudRain,
      FileWarning,
      Folder,
      Camera,
      Activity,
      AlertCircle,
      DollarSign,
      Eye,
      Edit,
      Trash2,
    }),
  ],
  exports: [LucideAngularModule],
})
export class LucideIconsModule {}
