import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, HardHat, Store, Package, Users, ArrowLeft, Check, Edit, ClipboardList, DollarSign, UserCheck, UserPlus, TrendingUp, Star, Rocket, ArrowRight, RotateCcw } from 'lucide-angular';
import { BomService } from '../../../services/bom.service';
import { BiddingService } from '../../../../../services/bidding.service';
import { UserService } from '../../../../../services/user.service';
import { RatingService } from '../../../../../services/rating.service';
import { MatSnackBar } from '@angular/material/snack-bar';
import { forkJoin, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';

  interface Bid {
      id: number;
      companyName: string;
      rating: number;
      location: string;
      price: number;
      leadTime: string;
      verified: boolean;
      status: string;
  }

  interface TradePackage {
      id: string;
      jobId: number;
      trade: string;
      category: 'trade' | 'vendor' | 'equipment' | 'supplier';
      icon?: string;
      scopeOfWork: string;
      estimatedManHours: number;
      durationDays: number | null;
      hourlyRate: number;
      laborBudget: number;
      materialBudget: number;
      totalBudget: number;
      effectiveBudget: number;
      estimatedDuration: string;
      startDate: string | null;
      laborType: string;
      status?: string;
      bidDeadline?: string | null;
      createdAt?: string;
      csiCode: string;
      linkedTradePackageId?: number | null;
      isAutoGenerated?: boolean;
      isInactive?: boolean;
      isHidden?: boolean;
      sourceType?: string | null;
      isInHouse?: boolean;
      budget: number;
      bidType: string;
      postedToMarketplace: boolean;
      bids: Bid[];
      hasInternalQuote: boolean;
  }

@Component({
  selector: 'app-job-inbound-bidding',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './job-inbound-bidding.component.html',
  styleUrls: ['./job-inbound-bidding.component.scss']
})
export class JobInboundBiddingComponent implements OnInit {
  @Input() projectDetails: any;
  @Output() back = new EventEmitter<void>();
  @Output() goLive = new EventEmitter<void>();

  activeTab: 'trades' | 'vendors' | 'suppliers' = 'trades';
  isLoading = false;

  HardHat = HardHat;
  Store = Store;
  Package = Package;
  Users = Users;
  ArrowLeft = ArrowLeft;
  Check = Check;
  Edit = Edit;
  ClipboardList = ClipboardList;
  DollarSign = DollarSign;
  UserCheck = UserCheck;
  UserPlus = UserPlus;
  TrendingUp = TrendingUp;
  Star = Star;
  Rocket = Rocket;
  ArrowRight = ArrowRight;
  RotateCcw = RotateCcw;

  tradePackages: TradePackage[] = [];
  showAllInHouseConfirm = false;
  pendingAllInHouseCount = 0;

  constructor(
    private bomService: BomService,
    private biddingService: BiddingService,
    private userService: UserService,
    private ratingService: RatingService,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit() {
    if (this.projectDetails?.jobId) {
      // Auto-refresh on first entry so users don't have to click the button manually
      this.refreshPackages(false);
    }
  }

  loadPackages(jobId: string) {
    this.isLoading = true;
    this.bomService.getTradePackages(jobId).subscribe({
      next: (packages) => {
        this.tradePackages = packages.map(pkg => {
          const laborBudget = Number(pkg.laborBudget || 0);
          const materialBudget = Number(pkg.materialBudget || 0);
          const totalBudget = Number(
            pkg.totalBudget ||
              (laborBudget + materialBudget > 0 ? laborBudget + materialBudget : 0) ||
              pkg.budget ||
              0,
          );
          const normalizedLaborType = String(pkg.laborType || '').trim().toLowerCase();
          const isLaborOnly = normalizedLaborType === 'labor' || normalizedLaborType === 'labor only';
          const effectiveBudget = Number(
            pkg.effectiveBudget || (isLaborOnly ? laborBudget : totalBudget) || pkg.budget || 0,
          );

          return {
            ...pkg,
            trade: pkg.trade.replace(/\*\*/g, ''),
            laborBudget,
            materialBudget,
            totalBudget,
            effectiveBudget,
            budget: effectiveBudget,
          };
        });
        this.tradePackages.forEach((pkg) => this.recalculateBudgets(pkg));
        this.loadBids(jobId);
      },
      error: (err) => {
        console.error('Failed to load trade packages', err);
        this.isLoading = false;
      },
    });
  }

  loadBids(jobId: string) {
    this.biddingService.getBidsForJob(Number(jobId)).subscribe({
      next: (bids: any[]) => {
        if (!bids || bids.length === 0) {
          this.isLoading = false;
          return;
        }

        // Enrich bids with user details and ratings
        const bidObservables = bids.map((b) => {
          const userId = b.userId;
          if (!userId) {
            return of({
              ...b,
              companyName: 'Unknown Contractor',
              rating: 0,
              location: 'Unknown',
            });
          }

          const user$ = this.userService.getUserById(userId).pipe(
            catchError(() => of(null))
          );
          const rating$ = this.ratingService.getRatingsForUser(userId).pipe(
            catchError(() => of([]))
          );

          return forkJoin([user$, rating$]).pipe(
            map(([user, ratings]) => {
              const avgRating =
                ratings && ratings.length > 0
                  ? ratings.reduce((acc: number, r: any) => acc + r.rating, 0) /
                    ratings.length
                  : 0;

              const location = user?.city && user?.state
                  ? `${user.city}, ${user.state}`
                  : (user?.city || 'Unknown Location');

              return {
                ...b,
                companyName: user
                  ? `${user.firstName} ${user.lastName}`
                  : 'Unknown Contractor',
                rating: avgRating,
                location: location,
              };
            })
          );
        });

        forkJoin(bidObservables).subscribe((enrichedBids: any[]) => {
          this.tradePackages.forEach((pkg) => {
            const relevantBids = enrichedBids.filter(
              (b) => b.task === pkg.trade || b.task === pkg.id
            );

            pkg.bids = relevantBids.map((b: any) => ({
              id: b.id,
              companyName: b.companyName,
              rating: b.rating,
              location: b.location,
              price: b.amount,
              leadTime: b.duration ? b.duration + ' days' : 'N/A',
              verified: false, // Could be derived from user verification status
              status: b.status,
            }));
          });
          this.isLoading = false;
        });
      },
      error: (err) => {
        console.error('Failed to load bids', err);
        this.isLoading = false;
      },
    });
  }

  get filteredPackages() {
      // Mapping categories: 'trades' -> 'trade', 'vendors' -> 'vendor'/'equipment', 'suppliers' -> 'supplier'
      if (this.activeTab === 'trades') return this.tradePackages.filter(p => p.category === 'trade' && !p.isHidden && !p.isInactive);
      if (this.activeTab === 'vendors') return this.tradePackages.filter(p => p.category === 'vendor' || p.category === 'equipment');
      if (this.activeTab === 'suppliers') return this.tradePackages.filter(p => p.category === 'supplier' && !p.isHidden && !p.isInactive);
      return [];
  }

  get tradesCount() {
    return this.tradePackages.filter(
      (p) => p.category === 'trade' && !p.isHidden && !p.isInactive,
    ).length;
  }

  get vendorsCount() {
    return this.tradePackages.filter(
      (p) => (p.category === 'vendor' || p.category === 'equipment') && !p.isHidden && !p.isInactive,
    ).length;
  }

  get suppliersCount() {
    return this.tradePackages.filter(p => p.category === 'supplier' && !p.isHidden && !p.isInactive).length;
  }

  get packagesReadyCount() {
      return this.tradePackages.filter(p => p.postedToMarketplace || p.hasInternalQuote || p.isInHouse).length;
  }

  private isPackageHandled(pkg: TradePackage): boolean {
    return !!(pkg.postedToMarketplace || pkg.hasInternalQuote || pkg.isInHouse);
  }

  get completedChecklistItems(): number {
    const tradesHandled = this.tradePackages.filter(
      (p) => p.category === 'trade' && !p.isHidden && !p.isInactive && this.isPackageHandled(p)
    ).length;

    const vendorsHandled = this.tradePackages.filter(
      (p) => (p.category === 'vendor' || p.category === 'equipment') && !p.isHidden && !p.isInactive && this.isPackageHandled(p)
    ).length;

    const suppliersHandled = this.tradePackages.filter(
      (p) => p.category === 'supplier' && !p.isHidden && !p.isInactive && this.isPackageHandled(p)
    ).length;

    return tradesHandled + vendorsHandled + suppliersHandled;
  }

  get totalChecklistItems(): number {
    return this.tradesCount + this.vendorsCount + this.suppliersCount;
  }

  get checklistCompletionPercent(): number {
    if (this.totalChecklistItems === 0) {
      return 0;
    }

    return (this.completedChecklistItems / this.totalChecklistItems) * 100;
  }

  get allChecklistItemsComplete(): boolean {
    return this.totalChecklistItems > 0 && this.completedChecklistItems === this.totalChecklistItems;
  }

  markAllInHouse(): void {
    const candidates = this.tradePackages.filter((p) => !p.isInHouse);
    if (candidates.length === 0) {
      this.snackBar.open('All packages are already marked as in-house', 'Close', { duration: 2500 });
      return;
    }

    this.pendingAllInHouseCount = candidates.length;
    this.showAllInHouseConfirm = true;
  }

  cancelAllInHouse(): void {
    this.showAllInHouseConfirm = false;
    this.pendingAllInHouseCount = 0;
  }

  confirmAllInHouse(): void {
    const candidates = this.tradePackages.filter((p) => !p.isInHouse);
    if (candidates.length === 0) {
      this.cancelAllInHouse();
      this.snackBar.open('All packages are already marked as in-house', 'Close', { duration: 2500 });
      return;
    }

    this.showAllInHouseConfirm = false;

    const updates = candidates.map((pkg) => {
      const previousState = {
        isInHouse: !!pkg.isInHouse,
        postedToMarketplace: !!pkg.postedToMarketplace,
        status: pkg.status,
      };

      pkg.isInHouse = true;
      pkg.postedToMarketplace = false;
      pkg.status = 'In House';

      const updatePayload = this.buildTradePackageUpdatePayload(pkg);
      return this.bomService.updateTradePackage(Number(pkg.id), updatePayload).pipe(
        map(() => ({ success: true })),
        catchError((err) => {
          pkg.isInHouse = previousState.isInHouse;
          pkg.postedToMarketplace = previousState.postedToMarketplace;
          pkg.status = previousState.status;
          console.error('Failed to mark package as in-house', err);
          return of({ success: false });
        })
      );
    });

    forkJoin(updates).subscribe((results) => {
      const successCount = results.filter((r) => r.success).length;
      const failedCount = results.length - successCount;

      if (failedCount > 0) {
        this.snackBar.open(
          `${successCount} package(s) set to in-house, ${failedCount} failed`,
          'Close',
          { duration: 3500 }
        );
        this.pendingAllInHouseCount = 0;
        return;
      }

      this.snackBar.open(`All ${successCount} package(s) marked as in-house`, 'Close', { duration: 3000 });
      this.pendingAllInHouseCount = 0;
    });
  }

  markInHouse(pkg: TradePackage): void {
    const previousStatus = pkg.status;
    pkg.isInHouse = true;
    pkg.postedToMarketplace = false;
    pkg.status = 'In House';

    const updatePayload = this.buildTradePackageUpdatePayload(pkg);
    this.bomService.updateTradePackage(Number(pkg.id), updatePayload).subscribe({
      next: () => {
        this.snackBar.open(`${pkg.trade} marked as in-house`, 'Close', { duration: 3000 });
      },
      error: (err) => {
        console.error('Failed to mark package as in-house', err);
        pkg.isInHouse = false;
        pkg.status = previousStatus;
        this.snackBar.open(`Failed to mark ${pkg.trade} as in-house`, 'Close', { duration: 3000 });
      }
    });
  }

  onEstimatedManHoursChanged(pkg: TradePackage, rawValue: string): void {
    const manHours = Number(rawValue);
    const safeManHours = Number.isFinite(manHours) && manHours >= 0 ? manHours : 0;

    pkg.estimatedManHours = safeManHours;
    const derivedDays = this.calculateDurationDaysFromHours(safeManHours);
    pkg.durationDays = derivedDays;
    pkg.estimatedDuration = derivedDays ? `${derivedDays} days` : '';
    this.recalculateBudgets(pkg);
  }

  onDurationDaysChanged(pkg: TradePackage, rawValue: string): void {
    const days = Number(rawValue);
    const safeDays = Number.isFinite(days) && days > 0 ? Math.ceil(days) : null;

    pkg.durationDays = safeDays;
    pkg.estimatedDuration = safeDays ? `${safeDays} days` : '';
    pkg.estimatedManHours = safeDays ? safeDays * 8 : 0;
    this.recalculateBudgets(pkg);
  }

  onStartDateChanged(pkg: TradePackage, rawValue: string): void {
    pkg.startDate = rawValue || null;
  }

  onLaborTypeChanged(pkg: TradePackage, laborType: 'Labor and Materials' | 'Labor'): void {
    pkg.laborType = laborType;
    pkg.bidType = laborType === 'Labor' ? 'labor-only' : 'labor-material';
    this.recalculateBudgets(pkg);

    this.bomService
      .syncLaborTypeAndSupplierLink(
        Number(pkg.id),
        laborType,
        this.getAiTotalEstimate(pkg),
        this.getAiLaborEstimate(pkg)
      )
      .subscribe({
      next: () => {
        if (this.projectDetails?.jobId) {
          this.loadPackages(this.projectDetails.jobId);
        }
      },
      error: (err) => {
        console.error('Failed to sync labor type/supplier link', err);
        this.snackBar.open(`Failed to sync labor type for ${pkg.trade}`, 'Close', { duration: 3000 });
      },
    });
  }

  handlePostToMarketplace(pkg: TradePackage): void {
      if (pkg.isInHouse) {
        this.snackBar.open('In-house packages are not posted to marketplace', 'Close', { duration: 3000 });
        return;
      }

      const updatePayload = this.buildTradePackageUpdatePayload(pkg);

      this.bomService.updateTradePackage(Number(pkg.id), updatePayload).subscribe({
        next: () => {
          this.bomService.postTradePackage(pkg.id).subscribe({
            next: () => {
              pkg.postedToMarketplace = true;
              this.snackBar.open(`${pkg.trade} posted to marketplace`, 'Close', { duration: 3000 });
            },
            error: (err) => {
              console.error('Failed to post to marketplace', err);
              this.snackBar.open(`Failed to post ${pkg.trade} to marketplace`, 'Close', { duration: 3000 });
            }
          });
        },
        error: (err) => {
          console.error('Failed to save trade package updates before posting', err);
          this.snackBar.open(`Failed to save updates for ${pkg.trade}`, 'Close', { duration: 3000 });
        }
      });
  }

  private calculateDurationDaysFromHours(hours: number): number | null {
    if (!Number.isFinite(hours) || hours <= 0) {
      return null;
    }
    return Math.max(1, Math.ceil(hours / 8));
  }

  isLaborOnly(pkg: TradePackage): boolean {
    const normalized = String(pkg.laborType || '').trim().toLowerCase();
    return normalized === 'labor' || normalized === 'labor only';
  }

  getAiLaborEstimate(pkg: TradePackage): number {
    if (pkg.category === 'supplier') {
      return 0;
    }

    const storedLabor = Number(pkg.laborBudget || 0);
    if (storedLabor > 0) {
      return storedLabor;
    }

    return Number(pkg.estimatedManHours || 0) * Number(pkg.hourlyRate || 0);
  }

  getAiTotalEstimate(pkg: TradePackage): number {
    if (pkg.category === 'supplier') {
      return Number(pkg.materialBudget || pkg.totalBudget || pkg.effectiveBudget || pkg.budget || 0);
    }

    const fallback = this.getAiLaborEstimate(pkg) + Number(pkg.materialBudget || 0);
    return Number(pkg.totalBudget || fallback);
  }

  getEstimateLabel(pkg: TradePackage): string {
    if (pkg.category === 'supplier') {
      return `AI Materials: $${Number(this.getAiTotalEstimate(pkg) || 0).toLocaleString()}`;
    }

    return `AI Labor: $${Number(this.getAiLaborEstimate(pkg) || 0).toLocaleString()} | AI Total: $${Number(this.getAiTotalEstimate(pkg) || 0).toLocaleString()}`;
  }

  getEffectiveModeLabel(pkg: TradePackage): string {
    if (pkg.category === 'supplier') {
      return 'Materials';
    }

    return this.isLaborOnly(pkg) ? 'Labor Only' : 'Labor + Materials';
  }

  getEffectiveBudget(pkg: TradePackage): number {
    return this.isLaborOnly(pkg) ? this.getAiLaborEstimate(pkg) : this.getAiTotalEstimate(pkg);
  }

  private recalculateBudgets(pkg: TradePackage): void {
    const labor = this.getAiLaborEstimate(pkg);
    const totalFromPkg = Number(pkg.totalBudget || 0);
    const total = totalFromPkg > 0 ? totalFromPkg : Math.max(labor, Number(pkg.budget || 0));

    pkg.laborBudget = labor;
    pkg.totalBudget = total;
    pkg.materialBudget = Math.max(0, total - labor);
    pkg.effectiveBudget = this.getEffectiveBudget(pkg);
    pkg.budget = pkg.effectiveBudget;
  }

  private buildTradePackageUpdatePayload(pkg: TradePackage): any {
    this.recalculateBudgets(pkg);

    return {
      id: Number(pkg.id),
      jobId: Number(pkg.jobId),
      tradeName: pkg.trade,
      category: pkg.category,
      scopeOfWork: pkg.scopeOfWork,
      budget: Number(pkg.effectiveBudget || pkg.budget || 0),
      laborBudget: Number(pkg.laborBudget || 0),
      materialBudget: Number(pkg.materialBudget || 0),
      totalBudget: Number(pkg.totalBudget || 0),
      effectiveBudget: Number(pkg.effectiveBudget || pkg.budget || 0),
      status: pkg.status || (pkg.postedToMarketplace ? 'Posted' : 'Draft'),
      estimatedManHours: Number(pkg.estimatedManHours || 0),
      hourlyRate: Number(pkg.hourlyRate || 0),
      estimatedDuration: pkg.estimatedDuration || null,
      startDate: pkg.startDate || null,
      bidDeadline: pkg.bidDeadline || null,
      laborType: pkg.laborType || 'Labor and Materials',
      csiCode: pkg.csiCode,
      linkedTradePackageId: pkg.linkedTradePackageId || null,
      isAutoGenerated: !!pkg.isAutoGenerated,
      isInactive: !!pkg.isInactive,
      isHidden: !!pkg.isHidden,
      sourceType: pkg.sourceType || null,
      isInHouse: !!pkg.isInHouse,
      postedToMarketplace: !!pkg.postedToMarketplace,
      createdAt: pkg.createdAt || new Date().toISOString(),
    };
  }

  onGoLive() {
      this.goLive.emit();
  }

  refreshPackages(showToast: boolean = true) {
    if (!this.projectDetails?.jobId) return;

    this.isLoading = true;
    this.bomService.refreshTradePackages(this.projectDetails.jobId).subscribe({
      next: () => {
        if (showToast) {
          this.snackBar.open('Trade packages refreshed', 'Close', { duration: 3000 });
        }
        this.loadPackages(this.projectDetails.jobId);
      },
      error: (err) => {
        console.error('Failed to refresh packages', err);
        if (showToast) {
          this.snackBar.open('Failed to refresh trade packages', 'Close', { duration: 3000 });
        }
        this.loadPackages(this.projectDetails.jobId);
        this.isLoading = false;
      }
    });
  }
}
