import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, HardHat, Store, Package, Users, ArrowLeft, Check, Edit, ClipboardList, DollarSign, UserCheck, UserPlus, TrendingUp, Star, Rocket, ArrowRight, RotateCcw, ChevronDown, Eye, EyeOff, MessageSquare, Building2, Truck, Send, X, Mail, Phone, Shield, CheckCircle2, Zap } from 'lucide-angular';
import { BomService, SaveTradePackageBidInvitesRequest } from '../../../services/bom.service';
import { BiddingService } from '../../../../../services/bidding.service';
import { UserService } from '../../../../../services/user.service';
import { RatingService } from '../../../../../services/rating.service';
import { TeamManagementService, SendSubcontractorInviteRequest } from '../../../../../services/team-management.service';
import { ExternalDataService } from '../../../../../services/external-data.service';
import { MatSnackBar } from '@angular/material/snack-bar';
import { forkJoin, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import { ExternalCompanyWithContacts } from '../../../../../models/external-data';

  interface Bid {
      id: number;
      companyName: string;
      rating: number;
      location: string;
      price: number;
      leadTime: string;
      verified: boolean;
      status: string;
  }

  interface TradePackage {
      id: string;
      jobId: number;
      trade: string;
      category: 'trade' | 'vendor' | 'equipment' | 'supplier';
      icon?: string;
      scopeOfWork: string;
      estimatedManHours: number;
      durationDays: number | null;
      hourlyRate: number;
      laborBudget: number;
      materialBudget: number;
      totalBudget: number;
      effectiveBudget: number;
      estimatedDuration: string;
      startDate: string | null;
      laborType: string;
      status?: string;
      bidDeadline?: string | null;
      createdAt?: string;
      csiCode: string;
      linkedTradePackageId?: number | null;
      isAutoGenerated?: boolean;
      isInactive?: boolean;
      isHidden?: boolean;
      sourceType?: string | null;
      isInHouse?: boolean;
      budget: number;
      bidType: string;
      postedToMarketplace: boolean;
      bids: Bid[];
      hasInternalQuote: boolean;
      notes?: string | null;
      laborBudgetVisible?: boolean;
      materialBudgetVisible?: boolean;
  }

  interface InviteCandidate {
    name: string;
    company: string;
    rating: number;
    responseTime: string;
    specialty: string;
  }

@Component({
  selector: 'app-job-inbound-bidding',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  templateUrl: './job-inbound-bidding.component.html',
  styleUrls: ['./job-inbound-bidding.component.scss']
})
export class JobInboundBiddingComponent implements OnInit {
  @Input() projectDetails: any;
  @Output() back = new EventEmitter<void>();
  @Output() goLive = new EventEmitter<void>();

  activeTab: 'trades' | 'vendors' | 'suppliers' = 'trades';
  isLoading = false;

  HardHat = HardHat;
  Store = Store;
  Package = Package;
  Users = Users;
  ArrowLeft = ArrowLeft;
  Check = Check;
  Edit = Edit;
  ClipboardList = ClipboardList;
  DollarSign = DollarSign;
  UserCheck = UserCheck;
  UserPlus = UserPlus;
  TrendingUp = TrendingUp;
  Star = Star;
  Rocket = Rocket;
  ArrowRight = ArrowRight;
  RotateCcw = RotateCcw;
  ChevronDown = ChevronDown;
  Eye = Eye;
  EyeOff = EyeOff;
  MessageSquare = MessageSquare;
  Building2 = Building2;
  Truck = Truck;
  Send = Send;
  X = X;
  Mail = Mail;
  Phone = Phone;
  Shield = Shield;
  CheckCircle2 = CheckCircle2;
  Zap = Zap;

  tradePackages: TradePackage[] = [];
  showAllInHouseConfirm = false;
  pendingAllInHouseCount = 0;
  expandedPackageIds = new Set<string>();
  hiddenLaborBudgetIds = new Set<string>();
  hiddenMaterialsBudgetIds = new Set<string>();
  packageNotes: Record<string, string> = {};
  isSavingPackage = false;

  private packageSaveTimers: Record<string, any> = {};

  private roundCurrency(value: number): number {
    if (!Number.isFinite(value)) return 0;
    return Math.round((value + Number.EPSILON) * 100) / 100;
  }

  directInviteOpen = false;
  directInvitePkg: TradePackage | null = null;
  directInviteName = '';
  directInviteEmail = '';
  directInvitePhone = '';
  directInviteAlsoMarketplace = false;
  directInviteSelected = new Set<number>();
  directInviteSendConfirmOpen = false;

  recommendedCompanies: ExternalCompanyWithContacts[] = [];
  recommendedCompaniesLoading = false;
  recommendedCompaniesError = '';

  marketplaceConfirmOpen = false;
  marketplaceConfirmPkg: TradePackage | null = null;
  marketplaceConfirmSelected = new Set<number>();

  invitedCountByTradePackageId: Record<number, number> = {};

  readonly inviteCandidates: InviteCandidate[] = [
    { name: 'Marcus Rivera', company: 'Rivera Electric Co.', rating: 4.9, responseTime: '< 24 hrs', specialty: 'Commercial & Residential Electrical' },
    { name: 'James O\'Connor', company: 'O\'Connor Mechanical', rating: 4.8, responseTime: '< 12 hrs', specialty: 'HVAC & Plumbing' },
    { name: 'Sarah Mitchell', company: 'Mitchell Plumbing LLC', rating: 4.9, responseTime: '< 6 hrs', specialty: 'Residential Plumbing' },
    { name: 'Robert Kowalski', company: 'Kowalski Roofing', rating: 4.6, responseTime: '< 24 hrs', specialty: 'Roofing & Waterproofing' },
  ];

  constructor(
    private bomService: BomService,
    private biddingService: BiddingService,
    private userService: UserService,
    private ratingService: RatingService,
    private teamManagementService: TeamManagementService,
    private externalDataService: ExternalDataService,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit() {
    if (this.projectDetails?.jobId) {
      // Auto-refresh on first entry so users don't have to click the button manually
      this.refreshPackages(false);
    }
  }

  loadPackages(jobId: string) {
    this.isLoading = true;
    this.bomService.getTradePackages(jobId).subscribe({
      next: (packages) => {
        this.tradePackages = packages.map(pkg => {
          const laborBudget = Number(pkg.laborBudget || 0);
          const materialBudget = Number(pkg.materialBudget || 0);
          const totalBudget = Number(
            pkg.totalBudget ||
              (laborBudget + materialBudget > 0 ? laborBudget + materialBudget : 0) ||
              pkg.budget ||
              0,
          );
          const normalizedLaborType = String(pkg.laborType || '').trim().toLowerCase();
          const isLaborOnly = normalizedLaborType === 'labor' || normalizedLaborType === 'labor only';
          const effectiveBudget = Number(
            pkg.effectiveBudget || (isLaborOnly ? laborBudget : totalBudget) || pkg.budget || 0,
          );

          return {
            ...pkg,
            trade: pkg.trade.replace(/\*\*/g, ''),
            laborBudget,
            materialBudget,
            totalBudget,
            effectiveBudget,
            budget: effectiveBudget,
            notes: pkg.notes || '',
            laborBudgetVisible: pkg.laborBudgetVisible !== false,
            materialBudgetVisible: pkg.materialBudgetVisible !== false,
          };
        });

        this.packageNotes = this.tradePackages.reduce((acc, pkg) => {
          acc[pkg.id] = pkg.notes || '';
          return acc;
        }, {} as Record<string, string>);

        this.hiddenLaborBudgetIds = new Set(
          this.tradePackages
            .filter((pkg) => pkg.laborBudgetVisible === false)
            .map((pkg) => pkg.id),
        );

        this.hiddenMaterialsBudgetIds = new Set(
          this.tradePackages
            .filter((pkg) => pkg.materialBudgetVisible === false)
            .map((pkg) => pkg.id),
        );

        this.tradePackages.forEach((pkg) => this.recalculateBudgets(pkg));
        this.loadBids(jobId);

        this.bomService.getBidInviteCountsForJob(jobId).subscribe({
          next: (rows) => {
            console.log('Bid invite counts loaded for jobId', jobId, rows);
            const nextMap: Record<number, number> = {};
            (rows || []).forEach((r: any) => {
              const id = Number(r.tradePackageId);
              const count = Number(r.invitedCount);
              if (Number.isFinite(id) && Number.isFinite(count)) {
                nextMap[id] = count;
              }
            });
            this.invitedCountByTradePackageId = nextMap;

            if (!rows || rows.length === 0) {
              console.warn('Bid invite counts endpoint returned empty list for jobId', jobId);
            }
          },
          error: () => {
            console.error('Failed to load bid invite counts');
          },
        });
      },
      error: (err) => {
        console.error('Failed to load trade packages', err);
        this.isLoading = false;
      },
    });
  }

  loadBids(jobId: string) {
    this.biddingService.getBidsForJob(Number(jobId)).subscribe({
      next: (bids: any[]) => {
        if (!bids || bids.length === 0) {
          this.isLoading = false;
          return;
        }

        // Enrich bids with user details and ratings
        const bidObservables = bids.map((b) => {
          const userId = b.userId;
          if (!userId) {
            return of({
              ...b,
              companyName: 'Unknown Contractor',
              rating: 0,
              location: 'Unknown',
            });
          }

          const user$ = this.userService.getUserById(userId).pipe(
            catchError(() => of(null))
          );
          const rating$ = this.ratingService.getRatingsForUser(userId).pipe(
            catchError(() => of([]))
          );

          return forkJoin([user$, rating$]).pipe(
            map(([user, ratings]) => {
              const avgRating =
                ratings && ratings.length > 0
                  ? ratings.reduce((acc: number, r: any) => acc + r.rating, 0) /
                    ratings.length
                  : 0;

              const location = user?.city && user?.state
                  ? `${user.city}, ${user.state}`
                  : (user?.city || 'Unknown Location');

              return {
                ...b,
                companyName: user
                  ? `${user.firstName} ${user.lastName}`
                  : 'Unknown Contractor',
                rating: avgRating,
                location: location,
              };
            })
          );
        });

        forkJoin(bidObservables).subscribe((enrichedBids: any[]) => {
          this.tradePackages.forEach((pkg) => {
            const relevantBids = enrichedBids.filter(
              (b) => b.task === pkg.trade || b.task === pkg.id
            );

            pkg.bids = relevantBids.map((b: any) => ({
              id: b.id,
              companyName: b.companyName,
              rating: b.rating,
              location: b.location,
              price: b.amount,
              leadTime: b.duration ? b.duration + ' days' : 'N/A',
              verified: false, // Could be derived from user verification status
              status: b.status,
            }));
          });
          this.isLoading = false;
        });
      },
      error: (err) => {
        console.error('Failed to load bids', err);
        this.isLoading = false;
      },
    });
  }

  get filteredPackages() {
      // Mapping categories: 'trades' -> 'trade', 'vendors' -> 'vendor'/'equipment', 'suppliers' -> 'supplier'
      if (this.activeTab === 'trades') return this.tradePackages.filter(p => p.category === 'trade' && !p.isHidden && !p.isInactive);
      if (this.activeTab === 'vendors') return this.tradePackages.filter(p => p.category === 'vendor' || p.category === 'equipment');
      if (this.activeTab === 'suppliers') return this.tradePackages.filter(p => p.category === 'supplier' && !p.isHidden && !p.isInactive);
      return [];
  }

  isExpanded(pkgId: string): boolean {
    return this.expandedPackageIds.has(pkgId);
  }

  toggleExpanded(pkgId: string): void {
    const next = new Set(this.expandedPackageIds);
    if (next.has(pkgId)) {
      next.delete(pkgId);
    } else {
      next.add(pkgId);
    }
    this.expandedPackageIds = next;
  }

  expandAllVisible(): void {
    this.expandedPackageIds = new Set(this.filteredPackages.map((pkg) => pkg.id));
  }

  collapseAllVisible(): void {
    const next = new Set(this.expandedPackageIds);
    this.filteredPackages.forEach((pkg) => next.delete(pkg.id));
    this.expandedPackageIds = next;
  }

  get allVisibleExpanded(): boolean {
    return this.filteredPackages.length > 0 && this.filteredPackages.every((pkg) => this.expandedPackageIds.has(pkg.id));
  }

  get allVisibleCollapsed(): boolean {
    return this.filteredPackages.every((pkg) => !this.expandedPackageIds.has(pkg.id));
  }

  getCategoryIcon(pkg: TradePackage) {
    if (pkg.category === 'supplier') return this.Truck;
    if (pkg.category === 'vendor' || pkg.category === 'equipment') return this.Store;
    return this.HardHat;
  }

  getCategoryLabel(pkg: TradePackage): string {
    if (pkg.category === 'supplier') return 'Supplier';
    if (pkg.category === 'vendor' || pkg.category === 'equipment') return 'Vendor';
    return 'Trade';
  }

  onBudgetChanged(pkg: TradePackage, rawValue: string): void {
    if (pkg.postedToMarketplace) return;
    const budget = Number(rawValue);
    const safeBudget = Number.isFinite(budget) && budget >= 0 ? budget : 0;
    pkg.budget = safeBudget;
    pkg.effectiveBudget = safeBudget;
  }

  getAiMaterialsEstimate(pkg: TradePackage): number {
    return this.roundCurrency(
      Math.max(0, this.getAiTotalEstimate(pkg) - this.getAiLaborEstimate(pkg)),
    );
  }

  onLaborBudgetChanged(pkg: TradePackage, rawValue: string): void {
    if (pkg.postedToMarketplace) return;
    const next = Number(rawValue);
    const safe = Number.isFinite(next) && next >= 0 ? next : 0;
    pkg.laborBudget = this.roundCurrency(safe);
    pkg.totalBudget = this.roundCurrency(
      Math.max(0, Number(pkg.materialBudget || 0) + pkg.laborBudget),
    );
    pkg.effectiveBudget = this.getEffectiveBudget(pkg);
    pkg.effectiveBudget = this.roundCurrency(pkg.effectiveBudget);
    pkg.budget = pkg.effectiveBudget;
    this.schedulePersistPackageEdits(pkg);
  }

  onMaterialBudgetChanged(pkg: TradePackage, rawValue: string): void {
    if (pkg.postedToMarketplace) return;
    const next = Number(rawValue);
    const safe = Number.isFinite(next) && next >= 0 ? next : 0;
    pkg.materialBudget = this.roundCurrency(safe);
    pkg.totalBudget = this.roundCurrency(
      Math.max(0, Number(pkg.laborBudget || 0) + pkg.materialBudget),
    );
    pkg.effectiveBudget = this.getEffectiveBudget(pkg);
    pkg.effectiveBudget = this.roundCurrency(pkg.effectiveBudget);
    pkg.budget = pkg.effectiveBudget;
    this.schedulePersistPackageEdits(pkg);
  }

  private schedulePersistPackageEdits(pkg: TradePackage): void {
    const key = String(pkg.id);
    const existing = this.packageSaveTimers[key];
    if (existing) {
      clearTimeout(existing);
    }

    this.packageSaveTimers[key] = setTimeout(() => {
      delete this.packageSaveTimers[key];
      this.persistPackageEdits(pkg);
    }, 600);
  }

  getNotes(pkg: TradePackage): string {
    return this.packageNotes[pkg.id] || '';
  }

  setNotes(pkg: TradePackage, value: string): void {
    this.packageNotes[pkg.id] = value;
    pkg.notes = value;
  }

  saveNotes(pkg: TradePackage): void {
    if (pkg.postedToMarketplace) return;
    this.persistPackageEdits(pkg, 'Notes saved');
  }

  toggleVisibility(pkg: TradePackage, target: 'labor' | 'materials'): void {
    if (pkg.postedToMarketplace) return;
    const setToToggle = target === 'labor' ? this.hiddenLaborBudgetIds : this.hiddenMaterialsBudgetIds;
    const next = new Set(setToToggle);
    if (next.has(pkg.id)) {
      next.delete(pkg.id);
    } else {
      next.add(pkg.id);
    }

    if (target === 'labor') {
      this.hiddenLaborBudgetIds = next;
    } else {
      this.hiddenMaterialsBudgetIds = next;
    }

    this.persistPackageEdits(pkg);
  }

  isVisibilityHidden(pkg: TradePackage, target: 'labor' | 'materials'): boolean {
    return target === 'labor' ? this.hiddenLaborBudgetIds.has(pkg.id) : this.hiddenMaterialsBudgetIds.has(pkg.id);
  }

  showMaterialsVisibility(pkg: TradePackage): boolean {
    if (pkg.category === 'supplier') return true;
    if (pkg.category === 'vendor' || pkg.category === 'equipment') return true;
    return !this.isLaborOnly(pkg);
  }

  getPostActionLabel(pkg: TradePackage): string {
    if (pkg.category === 'supplier') return 'Request Supplier Quotes';
    if (pkg.category === 'vendor' || pkg.category === 'equipment') return 'Post to Vendor Marketplace';
    return 'Post to Marketplace';
  }

  onPlaceholderAction(action: 'directInvite', pkg: TradePackage): void {
    if (action === 'directInvite') {
      this.openDirectInvite(pkg);
    }
  }

  openDirectInvite(pkg: TradePackage): void {
    this.directInvitePkg = pkg;
    this.directInviteOpen = true;
    this.directInviteName = '';
    this.directInviteEmail = '';
    this.directInvitePhone = '';
    this.directInviteAlsoMarketplace = false;
    this.directInviteSelected = new Set<number>();

    this.loadRecommendedCompanies(pkg);
  }

  closeDirectInvite(): void {
    this.directInviteOpen = false;
    this.directInvitePkg = null;

    this.directInviteSendConfirmOpen = false;

    this.recommendedCompanies = [];
    this.recommendedCompaniesLoading = false;
    this.recommendedCompaniesError = '';
  }

  private parseGoogleRating(description: string | null | undefined): { rating: number | null; reviews: number | null } {
    if (!description) return { rating: null, reviews: null };

    const match = description.match(/google\s*rating\s*:\s*([0-9]+(?:[\.,][0-9]+)?)\s*\/\s*5\s*\((\d+)\s*reviews?\)/i);
    if (!match) return { rating: null, reviews: null };

    const rating = Number.parseFloat(String(match[1]).replace(',', '.'));
    const reviews = Number.parseInt(String(match[2]), 10);

    return {
      rating: Number.isFinite(rating) ? rating : null,
      reviews: Number.isFinite(reviews) ? reviews : null,
    };
  }

  getRecommendedGoogleRatingLabel(row: ExternalCompanyWithContacts): string {
    const parsed = this.parseGoogleRating(row?.company?.description);
    if (!parsed.rating) return 'Google: N/A';
    if (!parsed.reviews) return `Google: ${parsed.rating.toFixed(1)}`;
    return `Google: ${parsed.rating.toFixed(1)} (${parsed.reviews})`;
  }

  getRecommendedCompanyLocation(row: ExternalCompanyWithContacts): string {
    const parts = [row?.company?.city, row?.company?.state]
      .filter((x) => typeof x === 'string' && x.trim().length > 0)
      .map((x) => (x as string).trim());
    return parts.join(', ');
  }

  requestSendDirectInvites(): void {
    if (!this.directInvitePkg) return;

    if (this.directInviteCount === 0) {
      this.snackBar.open('Add at least one contact before sending invites.', 'Close', { duration: 2400 });
      return;
    }

    this.directInviteSendConfirmOpen = true;
  }

  cancelDirectInviteSendConfirm(): void {
    this.directInviteSendConfirmOpen = false;
  }

  confirmDirectInviteSend(): void {
    this.directInviteSendConfirmOpen = false;
    this.sendDirectInvites();
  }

  toggleDirectInviteCandidate(companyId: number): void {
      const next = new Set(this.directInviteSelected);
      if (next.has(companyId)) {
        next.delete(companyId);
      } else {
        next.add(companyId);
      }
      this.directInviteSelected = next;
    }

  private loadRecommendedCompanies(pkg: TradePackage): void {
    const tradeName = (pkg.trade || '').trim();
    if (!tradeName) {
      this.recommendedCompanies = [];
      this.recommendedCompaniesLoading = false;
      this.recommendedCompaniesError = '';
      return;
    }

    const jobId = Number(this.projectDetails?.jobId || pkg.jobId);
    const tradePackageId = Number(pkg.id);

    const city = (this.projectDetails?.city || this.projectDetails?.jobCity || this.projectDetails?.addressCity || '').toString().trim();
    const state = (this.projectDetails?.state || this.projectDetails?.jobState || this.projectDetails?.addressState || '').toString().trim();

    this.recommendedCompaniesLoading = true;
    this.recommendedCompaniesError = '';
    this.recommendedCompanies = [];

    this.externalDataService
      .discoverSubcontractors({
        tradePackageId: Number.isFinite(tradePackageId) ? tradePackageId : undefined,
        jobId: Number.isFinite(jobId) ? jobId : undefined,
        tradeName,
        city: city || undefined,
        state: state || undefined,
        radiusMiles: 25,
        limit: 20,
      })
      .subscribe({
        next: (results) => {
          this.recommendedCompanies = Array.isArray(results) ? results : [];
          this.recommendedCompaniesLoading = false;
        },
        error: () => {
          this.recommendedCompanies = [];
          this.recommendedCompaniesLoading = false;
          this.recommendedCompaniesError = 'Unable to load recommended contractors right now.';
        },
      });
  }

  getRecommendedCompanyEmail(row: ExternalCompanyWithContacts): string {
    const contacts = row?.contacts || [];
    const withEmail = contacts.find((c) => !!c.email?.trim());
    const contactEmail = (withEmail?.email || contacts[0]?.email || '').trim();
    if (contactEmail) {
      return contactEmail;
    }

    return (row?.company?.email || '').trim();
  }

  get directInviteCount(): number {
    const typedInvite = this.directInviteEmail.trim() ? 1 : 0;
    return typedInvite + this.directInviteSelected.size;
  }

  getInvitedCount(pkg: TradePackage): number {
    const id = Number(pkg?.id);
    if (!Number.isFinite(id)) {
      return 0;
    }
    return Number(this.invitedCountByTradePackageId[id] || 0);
  }

  sendDirectInvites(): void {
    if (!this.directInvitePkg) return;
    if (this.directInviteCount === 0) {
      this.snackBar.open('Add at least one contact before sending invites.', 'Close', { duration: 2400 });
      return;
    }

    const pkg = this.directInvitePkg;
    const postAfterInvite = this.directInviteAlsoMarketplace;
    const email = this.directInviteEmail.trim();
    const contactName = this.directInviteName.trim();
    const phoneNumber = this.directInvitePhone.trim();

    const parsedJobId = Number(this.projectDetails?.jobId || pkg.jobId);
    const parsedTradePackageId = Number(pkg.id);

    const inviteRequests: SendSubcontractorInviteRequest[] = [];
    if (email) {
      inviteRequests.push({
        email,
        contactName: contactName || null,
        phoneNumber: phoneNumber || null,
        jobId: Number.isFinite(parsedJobId) ? parsedJobId : null,
        tradePackageId: Number.isFinite(parsedTradePackageId) ? parsedTradePackageId : null,
        tradeName: pkg.trade,
        category: pkg.category,
        scopeOfWork: pkg.scopeOfWork || null,
        budget: Number(pkg.effectiveBudget || pkg.totalBudget || pkg.budget || 0),
        alsoMarketplace: postAfterInvite,
      });
    }

    const selectedCompanies = this.recommendedCompanies.filter((row) =>
      this.directInviteSelected.has(Number(row.company?.id || 0)),
    );

    const persistInvitees: SaveTradePackageBidInvitesRequest['invitees'] = [];
    selectedCompanies.forEach((row) => {
      const contact = (row.contacts || []).find((c) => !!c.email?.trim()) || (row.contacts || [])[0];
      const cEmail = (contact?.email || row.company?.email || '').trim();
      if (!cEmail) {
        return;
      }

      persistInvitees.push({
        email: cEmail,
        contactName: contact?.fullName || row.company?.name || null,
        companyName: row.company?.name || null,
        externalCompanyId: Number.isFinite(Number(row.company?.id)) ? Number(row.company?.id) : null,
        externalContactId: Number.isFinite(Number(contact?.id)) ? Number(contact?.id) : null,
      });

      inviteRequests.push({
        email: cEmail,
        contactName: contact?.fullName || row.company?.name || null,
        phoneNumber: contact?.phone || row.company?.phone || null,
        jobId: Number.isFinite(parsedJobId) ? parsedJobId : null,
        tradePackageId: Number.isFinite(parsedTradePackageId) ? parsedTradePackageId : null,
        tradeName: pkg.trade,
        category: pkg.category,
        scopeOfWork: pkg.scopeOfWork || null,
        budget: Number(pkg.effectiveBudget || pkg.totalBudget || pkg.budget || 0),
        alsoMarketplace: postAfterInvite,
      });
    });

    if (email) {
      persistInvitees.push({
        email,
        contactName: contactName || null,
        companyName: null,
        externalCompanyId: null,
        externalContactId: null,
      });
    }

    if (inviteRequests.length === 0) {
      this.snackBar.open('No email addresses found for the selected contractors.', 'Close', { duration: 3200 });
      return;
    }

    const persistPayload: SaveTradePackageBidInvitesRequest = {
      jobId: parsedJobId,
      tradePackageId: parsedTradePackageId,
      invitees: persistInvitees,
    };

    const inviteCalls = inviteRequests.map((req) =>
      this.teamManagementService.sendSubcontractorInvite(req).pipe(
        map(() => ({ success: true })),
        catchError((err) => {
          console.error('Failed to send subcontractor invite', err);
          return of({ success: false });
        }),
      ),
    );

    this.bomService
      .saveTradePackageBidInvites(parsedTradePackageId, persistPayload)
      .pipe(
        catchError((err) => {
          console.error('Failed to persist bid invites', err);
          this.snackBar.open('Invites were sent, but saving invite list failed. Count may not show after refresh.', 'Close', {
            duration: 4200,
          });
          return of(null);
        }),
      )
      .subscribe(() => {
        forkJoin(inviteCalls).subscribe((results) => {
          const failed = results.filter((r) => !r.success).length;
          const sent = results.length - failed;
          if (sent > 0) {
            const pkgId = Number(pkg.id);
            if (Number.isFinite(pkgId)) {
              this.invitedCountByTradePackageId[pkgId] =
                (this.invitedCountByTradePackageId[pkgId] || 0) + sent;
            }

            pkg.status = postAfterInvite ? 'Posted' : 'Invited';
            pkg.postedToMarketplace = postAfterInvite;

            this.persistPackageEdits(
              pkg,
              failed > 0
                ? `${sent} invite(s) sent, ${failed} failed.`
                : `${sent} invite(s) sent.`,
              () => {
                if (postAfterInvite) {
                  this.postPackageToMarketplace(pkg);
                }
              },
            );

            this.closeDirectInvite();
            return;
          }

          this.snackBar.open('Unable to send invites right now. Please try again.', 'Close', {
            duration: 3200,
          });
        });
      });
  }

  openMarketplaceConfirm(pkg: TradePackage): void {
    this.marketplaceConfirmPkg = pkg;
    this.marketplaceConfirmOpen = true;
    this.marketplaceConfirmSelected = new Set<number>();
  }

  closeMarketplaceConfirm(): void {
    this.marketplaceConfirmOpen = false;
    this.marketplaceConfirmPkg = null;
  }

  toggleMarketplaceInvite(index: number): void {
    const next = new Set(this.marketplaceConfirmSelected);
    if (next.has(index)) {
      next.delete(index);
    } else {
      next.add(index);
    }
    this.marketplaceConfirmSelected = next;
  }

  confirmMarketplacePost(): void {
    if (!this.marketplaceConfirmPkg) return;
    const pkg = this.marketplaceConfirmPkg;
    const inviteCount = this.marketplaceConfirmSelected.size;
    this.closeMarketplaceConfirm();
    this.postPackageToMarketplace(pkg, inviteCount);
  }

  get tradesCount() {
    return this.tradePackages.filter(
      (p) => p.category === 'trade' && !p.isHidden && !p.isInactive,
    ).length;
  }

  get vendorsCount() {
    return this.tradePackages.filter(
      (p) => (p.category === 'vendor' || p.category === 'equipment') && !p.isHidden && !p.isInactive,
    ).length;
  }

  get suppliersCount() {
    return this.tradePackages.filter(p => p.category === 'supplier' && !p.isHidden && !p.isInactive).length;
  }

  get packagesReadyCount() {
      return this.tradePackages.filter(p => p.postedToMarketplace || p.hasInternalQuote || p.isInHouse).length;
  }

  private isPackageHandled(pkg: TradePackage): boolean {
    return !!(pkg.postedToMarketplace || pkg.hasInternalQuote || pkg.isInHouse);
  }

  get completedChecklistItems(): number {
    const tradesHandled = this.tradePackages.filter(
      (p) => p.category === 'trade' && !p.isHidden && !p.isInactive && this.isPackageHandled(p)
    ).length;

    const vendorsHandled = this.tradePackages.filter(
      (p) => (p.category === 'vendor' || p.category === 'equipment') && !p.isHidden && !p.isInactive && this.isPackageHandled(p)
    ).length;

    const suppliersHandled = this.tradePackages.filter(
      (p) => p.category === 'supplier' && !p.isHidden && !p.isInactive && this.isPackageHandled(p)
    ).length;

    return tradesHandled + vendorsHandled + suppliersHandled;
  }

  get totalChecklistItems(): number {
    return this.tradesCount + this.vendorsCount + this.suppliersCount;
  }

  get checklistCompletionPercent(): number {
    if (this.totalChecklistItems === 0) {
      return 0;
    }

    return (this.completedChecklistItems / this.totalChecklistItems) * 100;
  }

  get allChecklistItemsComplete(): boolean {
    return this.totalChecklistItems > 0 && this.completedChecklistItems === this.totalChecklistItems;
  }

  markAllInHouse(): void {
    const candidates = this.tradePackages.filter((p) => !p.isInHouse);
    if (candidates.length === 0) {
      this.snackBar.open('All packages are already marked as in-house', 'Close', { duration: 2500 });
      return;
    }

    this.pendingAllInHouseCount = candidates.length;
    this.showAllInHouseConfirm = true;
  }

  cancelAllInHouse(): void {
    this.showAllInHouseConfirm = false;
    this.pendingAllInHouseCount = 0;
  }

  confirmAllInHouse(): void {
    const candidates = this.tradePackages.filter((p) => !p.isInHouse);
    if (candidates.length === 0) {
      this.cancelAllInHouse();
      this.snackBar.open('All packages are already marked as in-house', 'Close', { duration: 2500 });
      return;
    }

    this.showAllInHouseConfirm = false;

    const updates = candidates.map((pkg) => {
      const previousState = {
        isInHouse: !!pkg.isInHouse,
        postedToMarketplace: !!pkg.postedToMarketplace,
        status: pkg.status,
      };

      pkg.isInHouse = true;
      pkg.postedToMarketplace = false;
      pkg.status = 'In House';

      const updatePayload = this.buildTradePackageUpdatePayload(pkg);
      return this.bomService.updateTradePackage(Number(pkg.id), updatePayload).pipe(
        map(() => ({ success: true })),
        catchError((err) => {
          pkg.isInHouse = previousState.isInHouse;
          pkg.postedToMarketplace = previousState.postedToMarketplace;
          pkg.status = previousState.status;
          console.error('Failed to mark package as in-house', err);
          return of({ success: false });
        })
      );
    });

    forkJoin(updates).subscribe((results) => {
      const successCount = results.filter((r) => r.success).length;
      const failedCount = results.length - successCount;

      if (failedCount > 0) {
        this.snackBar.open(
          `${successCount} package(s) set to in-house, ${failedCount} failed`,
          'Close',
          { duration: 3500 }
        );
        this.pendingAllInHouseCount = 0;
        return;
      }

      this.snackBar.open(`All ${successCount} package(s) marked as in-house`, 'Close', { duration: 3000 });
      this.pendingAllInHouseCount = 0;
    });
  }

  markInHouse(pkg: TradePackage): void {
    const previousStatus = pkg.status;
    pkg.isInHouse = true;
    pkg.postedToMarketplace = false;
    pkg.status = 'In House';

    const updatePayload = this.buildTradePackageUpdatePayload(pkg);
    this.bomService.updateTradePackage(Number(pkg.id), updatePayload).subscribe({
      next: () => {
        this.snackBar.open(`${pkg.trade} marked as in-house`, 'Close', { duration: 3000 });
      },
      error: (err) => {
        console.error('Failed to mark package as in-house', err);
        pkg.isInHouse = false;
        pkg.status = previousStatus;
        this.snackBar.open(`Failed to mark ${pkg.trade} as in-house`, 'Close', { duration: 3000 });
      }
    });
  }

  revertInHouse(pkg: TradePackage): void {
    const previousState = {
      isInHouse: !!pkg.isInHouse,
      postedToMarketplace: !!pkg.postedToMarketplace,
      status: pkg.status,
    };

    pkg.isInHouse = false;
    pkg.postedToMarketplace = false;
    pkg.status = 'Draft';

    const updatePayload = this.buildTradePackageUpdatePayload(pkg);
    this.bomService.updateTradePackage(Number(pkg.id), updatePayload).subscribe({
      next: () => {
        this.snackBar.open(`${pkg.trade} reverted from in-house`, 'Close', { duration: 3000 });
      },
      error: (err) => {
        console.error('Failed to revert package from in-house', err);
        pkg.isInHouse = previousState.isInHouse;
        pkg.postedToMarketplace = previousState.postedToMarketplace;
        pkg.status = previousState.status;
        this.snackBar.open(`Failed to revert ${pkg.trade} from in-house`, 'Close', { duration: 3200 });
      }
    });
  }

  onEstimatedManHoursChanged(pkg: TradePackage, rawValue: string): void {
    const manHours = Number(rawValue);
    const safeManHours = Number.isFinite(manHours) && manHours >= 0 ? manHours : 0;

    pkg.estimatedManHours = safeManHours;
    const derivedDays = this.calculateDurationDaysFromHours(safeManHours);
    pkg.durationDays = derivedDays;
    pkg.estimatedDuration = derivedDays ? `${derivedDays} days` : '';
    this.recalculateBudgets(pkg);
  }

  onDurationDaysChanged(pkg: TradePackage, rawValue: string): void {
    const days = Number(rawValue);
    const safeDays = Number.isFinite(days) && days > 0 ? Math.ceil(days) : null;

    pkg.durationDays = safeDays;
    pkg.estimatedDuration = safeDays ? `${safeDays} days` : '';
    pkg.estimatedManHours = safeDays ? safeDays * 8 : 0;
    this.recalculateBudgets(pkg);
  }

  onStartDateChanged(pkg: TradePackage, rawValue: string): void {
    pkg.startDate = rawValue || null;
  }

  onLaborTypeChanged(pkg: TradePackage, laborType: 'Labor and Materials' | 'Labor'): void {
    pkg.laborType = laborType;
    pkg.bidType = laborType === 'Labor' ? 'labor-only' : 'labor-material';
    this.recalculateBudgets(pkg);

    this.bomService
      .syncLaborTypeAndSupplierLink(
        Number(pkg.id),
        laborType,
        this.getAiTotalEstimate(pkg),
        this.getAiLaborEstimate(pkg)
      )
      .subscribe({
      next: () => {
        if (this.projectDetails?.jobId) {
          this.loadPackages(this.projectDetails.jobId);
        }
      },
      error: (err) => {
        console.error('Failed to sync labor type/supplier link', err);
        this.snackBar.open(`Failed to sync labor type for ${pkg.trade}`, 'Close', { duration: 3000 });
      },
    });
  }

  handlePostToMarketplace(pkg: TradePackage): void {
      this.openMarketplaceConfirm(pkg);
  }

  private postPackageToMarketplace(pkg: TradePackage, invitesCount: number = 0): void {
      if (pkg.isInHouse) {
        this.snackBar.open('In-house packages are not posted to marketplace', 'Close', { duration: 3000 });
        return;
      }

      const updatePayload = this.buildTradePackageUpdatePayload(pkg);

      this.bomService.updateTradePackage(Number(pkg.id), updatePayload).subscribe({
        next: () => {
          this.bomService.postTradePackage(pkg.id).subscribe({
            next: () => {
              pkg.postedToMarketplace = true;
              const inviteSuffix = invitesCount > 0 ? ` (+${invitesCount} direct invite${invitesCount > 1 ? 's' : ''})` : '';
              this.snackBar.open(`${pkg.trade} posted to marketplace${inviteSuffix}`, 'Close', { duration: 3000 });
            },
            error: (err) => {
              console.error('Failed to post to marketplace', err);
              this.snackBar.open(`Failed to post ${pkg.trade} to marketplace`, 'Close', { duration: 3000 });
            }
          });
        },
        error: (err) => {
          console.error('Failed to save trade package updates before posting', err);
          this.snackBar.open(`Failed to save updates for ${pkg.trade}`, 'Close', { duration: 3000 });
        }
      });
  }

  private persistPackageEdits(
    pkg: TradePackage,
    successMessage?: string,
    onSuccess?: () => void,
  ): void {
    const payload = this.buildTradePackageUpdatePayload(pkg);
    this.isSavingPackage = true;

    this.bomService.updateTradePackage(Number(pkg.id), payload).subscribe({
      next: () => {
        this.isSavingPackage = false;
        if (successMessage) {
          this.snackBar.open(successMessage, 'Close', { duration: 2200 });
        }
        onSuccess?.();
      },
      error: (err) => {
        this.isSavingPackage = false;
        console.error('Failed to persist trade package edits', err);
        this.snackBar.open(`Failed to save updates for ${pkg.trade}`, 'Close', { duration: 2600 });
      },
    });
  }

  shouldShowMaterialsToProcure(pkg: TradePackage): boolean {
    return pkg.category === 'trade' && this.isLaborOnly(pkg) && Number(pkg.materialBudget || 0) > 0;
  }

  getMaterialsToProcure(pkg: TradePackage): Array<{ item: string; vendor: string; estimate: number }> {
    const materialsCost = Math.max(0, Number(pkg.materialBudget || 0));
    const prefix = (pkg.csiCode || '').substring(0, 5).trim();

    const split = (items: Array<{ item: string; vendor: string; ratio: number }>) =>
      items.map((it) => ({ ...it, estimate: Math.round(materialsCost * it.ratio) }));

    if (prefix === '06 10') {
      return split([
        { item: 'Framing Lumber', vendor: 'Lumber Supplier', ratio: 0.45 },
        { item: 'LVL Beams & Headers', vendor: 'Engineered Wood Supplier', ratio: 0.25 },
        { item: 'Sheathing (OSB/Plywood)', vendor: 'Lumber Supplier', ratio: 0.2 },
        { item: 'Fasteners & Hardware', vendor: 'Hardware Vendor', ratio: 0.1 },
      ]);
    }

    if (prefix === '07 01') {
      return split([
        { item: 'Roof Panels/Shingles', vendor: 'Roofing Supplier', ratio: 0.55 },
        { item: 'Underlayment & Flashing', vendor: 'Roofing Supplier', ratio: 0.25 },
        { item: 'Sealants & Fasteners', vendor: 'Hardware Vendor', ratio: 0.2 },
      ]);
    }

    return split([
      { item: 'Primary Materials', vendor: 'General Supplier', ratio: 0.6 },
      { item: 'Secondary Materials', vendor: 'General Supplier', ratio: 0.25 },
      { item: 'Consumables', vendor: 'Hardware Vendor', ratio: 0.15 },
    ]);
  }

  private calculateDurationDaysFromHours(hours: number): number | null {
    if (!Number.isFinite(hours) || hours <= 0) {
      return null;
    }
    return Math.max(1, Math.ceil(hours / 8));
  }

  isLaborOnly(pkg: TradePackage): boolean {
    const normalized = String(pkg.laborType || '').trim().toLowerCase();
    return normalized === 'labor' || normalized === 'labor only';
  }

  getAiLaborEstimate(pkg: TradePackage): number {
    if (pkg.category === 'supplier') {
      return 0;
    }

    const storedLabor = Number(pkg.laborBudget || 0);
    if (storedLabor > 0) {
      return storedLabor;
    }

    return Number(pkg.estimatedManHours || 0) * Number(pkg.hourlyRate || 0);
  }

  getAiTotalEstimate(pkg: TradePackage): number {
    if (pkg.category === 'supplier') {
      return Number(pkg.materialBudget || pkg.totalBudget || pkg.effectiveBudget || pkg.budget || 0);
    }

    const fallback = this.getAiLaborEstimate(pkg) + Number(pkg.materialBudget || 0);
    return Number(pkg.totalBudget || fallback);
  }

  getEstimateLabel(pkg: TradePackage): string {
    if (pkg.category === 'supplier') {
      return `AI Materials: $${Number(this.getAiTotalEstimate(pkg) || 0).toLocaleString()}`;
    }

    return `AI Labor: $${Number(this.getAiLaborEstimate(pkg) || 0).toLocaleString()} | AI Total: $${Number(this.getAiTotalEstimate(pkg) || 0).toLocaleString()}`;
  }

  getEffectiveModeLabel(pkg: TradePackage): string {
    if (pkg.category === 'supplier') {
      return 'Materials';
    }

    return this.isLaborOnly(pkg) ? 'Labor Only' : 'Labor + Materials';
  }

  getEffectiveBudget(pkg: TradePackage): number {
    return this.isLaborOnly(pkg) ? this.getAiLaborEstimate(pkg) : this.getAiTotalEstimate(pkg);
  }

  private recalculateBudgets(pkg: TradePackage): void {
    const labor = this.getAiLaborEstimate(pkg);
    const totalFromPkg = Number(pkg.totalBudget || 0);
    const total = totalFromPkg > 0 ? totalFromPkg : Math.max(labor, Number(pkg.budget || 0));

    pkg.laborBudget = labor;
    pkg.totalBudget = total;
    pkg.materialBudget = Math.max(0, total - labor);
    pkg.effectiveBudget = this.getEffectiveBudget(pkg);
    pkg.budget = pkg.effectiveBudget;
  }

  private buildTradePackageUpdatePayload(pkg: TradePackage): any {
    this.recalculateBudgets(pkg);

    return {
      id: Number(pkg.id),
      jobId: Number(pkg.jobId),
      tradeName: pkg.trade,
      category: pkg.category,
      scopeOfWork: pkg.scopeOfWork,
      budget: this.roundCurrency(Number(pkg.effectiveBudget || pkg.budget || 0)),
      laborBudget: this.roundCurrency(Number(pkg.laborBudget || 0)),
      materialBudget: this.roundCurrency(Number(pkg.materialBudget || 0)),
      totalBudget: this.roundCurrency(Number(pkg.totalBudget || 0)),
      effectiveBudget: this.roundCurrency(Number(pkg.effectiveBudget || pkg.budget || 0)),
      status: pkg.status || (pkg.postedToMarketplace ? 'Posted' : 'Draft'),
      estimatedManHours: Number(pkg.estimatedManHours || 0),
      hourlyRate: Number(pkg.hourlyRate || 0),
      estimatedDuration: pkg.estimatedDuration || null,
      startDate: pkg.startDate || null,
      bidDeadline: pkg.bidDeadline || null,
      laborType: pkg.laborType || 'Labor and Materials',
      csiCode: pkg.csiCode,
      linkedTradePackageId: pkg.linkedTradePackageId || null,
      isAutoGenerated: !!pkg.isAutoGenerated,
      isInactive: !!pkg.isInactive,
      isHidden: !!pkg.isHidden,
      sourceType: pkg.sourceType || null,
      isInHouse: !!pkg.isInHouse,
      postedToMarketplace: !!pkg.postedToMarketplace,
      notes: this.getNotes(pkg) || null,
      laborBudgetVisible: !this.hiddenLaborBudgetIds.has(pkg.id),
      materialBudgetVisible: !this.hiddenMaterialsBudgetIds.has(pkg.id),
      createdAt: pkg.createdAt || new Date().toISOString(),
    };
  }

  onGoLive() {
      this.goLive.emit();
  }

  refreshPackages(showToast: boolean = true) {
    if (!this.projectDetails?.jobId) return;

    this.isLoading = true;
    this.bomService.refreshTradePackages(this.projectDetails.jobId).subscribe({
      next: () => {
        if (showToast) {
          this.snackBar.open('Trade packages refreshed', 'Close', { duration: 3000 });
        }
        this.loadPackages(this.projectDetails.jobId);
      },
      error: (err) => {
        console.error('Failed to refresh packages', err);
        if (showToast) {
          this.snackBar.open('Failed to refresh trade packages', 'Close', { duration: 3000 });
        }
        this.loadPackages(this.projectDetails.jobId);
        this.isLoading = false;
      }
    });
  }
}
