name: Build and Deploy Frontend to Azure Container Apps

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Log in to Azure using Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"0e6dc202-bcae-4b8b-b1de-a8f3a04341d6"}'

      # Log in to Azure Container Registry
      - name: Log in to ACR
        run: |
          az acr login --name probuild

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image to ACR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: probuild.azurecr.io/probuildai-ui:${{ github.sha }}

      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name probuildai-ui \
            --resource-group rg-Probuild \
            --image probuild.azurecr.io/probuildai-ui:${{ github.sha }} \
            --set-env-vars \
              "PORT=8080" \
              "FORCE_NEW_REVISION=true" \
            --set ingress.targetPort=8080

      # Check logs to diagnose issues
      - name: Check Container App Logs
        run: |
          az containerapp logs show --name probuildai-ui --resource-group rg-Probuild --follow --tail 100
        continue-on-error: true
