name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Debug: Print the Service Principal credentials (values will be masked)
      - name: Debug Service Principal credentials
        run: |
          echo "AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}"
          echo "AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}"

      # Log in to Azure using Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"0e6dc202-bcae-4b8b-b1de-a8f3a04341d6"}'

      # Log in to Azure Container Registry
      - name: Log in to ACR
        run: |
          az acr login --name probuild

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image to ACR with dynamic tag
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: probuild.azurecr.io/probuildai-ui:${{ github.sha }}  # Use commit SHA as tag
          no-cache: true  # Force rebuild to avoid caching issues
        env:
          BACKEND_URL: "https://probuildai-backend.wonderfulgrass-0f331ae8.centralus.azurecontainerapps.io/api"
          API_KEY: "ef306472fbed4ca9835115255241412"
          Google_API : "AIzaSyBVEXpDDbV96oeuydmvV9F6Ew1Hq-6Psww"

      # Debug: Verify the image exists in ACR
      - name: Debug ACR image
        run: |
          az acr repository show-tags --name probuild --repository probuildai-ui --output table

      # Deploy to Azure Container App with retry mechanism
      - name: Deploy to Azure Container App
        run: |
          # Attempt to update the container app with retries
          for i in {1..3}; do
            echo "Attempt $i: Updating Azure Container App..."
            az containerapp update \
              --name probuildai-ui \
              --resource-group rg-Probuild \
              --image probuild.azurecr.io/probuildai-ui:${{ github.sha }} \
              --set "properties.environmentId=/subscriptions/0e6dc202-bcae-4b8b-b1de-a8f3a04341d6/resourceGroups/rg-Probuild/providers/Microsoft.App/managedEnvironments/managedEnvironment-rgProbuild-ae27" \
              --set "properties.configuration.activeRevisionsMode=Single" \
              --cpu 0.5 \
              --memory 1.0Gi \
              --min-replicas 1 \
              --max-replicas 1 \
              && break || echo "Update failed, retrying in 30 seconds..."
            sleep 30
          done

      # Debug: Verify the container app revision
      - name: Debug Container App Revision
        run: |
          az containerapp revision list --name probuildai-ui --resource-group rg-Probuild --output table

      # Debug: Check container app logs (optional, requires log analytics setup)
      - name: Check Container App Logs
        run: |
          az containerapp logs show \
            --name probuildai-ui \
            --resource-group rg-Probuild \
            --tail 50 \
            --format text || echo "Failed to fetch logs, ensure log analytics is enabled."
