name: Build and Deploy Frontend to Azure Container Apps

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Log in to Azure using Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"0e6dc202-bcae-4b8b-b1de-a8f3a04341d6"}'

      # Log in to Azure Container Registry
      - name: Log in to ACR
        run: |
          az acr login --name probuild

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image to ACR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: probuild.azurecr.io/probuildai-ui:${{ github.sha }}

      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        run: |
          # Check if the app already exists
          if az containerapp show --name probuildai-ui --resource-group rg-Probuild > /dev/null 2>&1; then
            echo "Container app exists, updating..."
            az containerapp update \
              --name probuildai-ui \
              --resource-group rg-Probuild \
              --image probuild.azurecr.io/probuildai-ui:${{ github.sha }} \
              --set-env-vars \
                "PORT=80" \
                "FORCE_NEW_REVISION=true"
          else
            echo "Container app does not exist, creating..."
            az containerapp create \
              --name probuildai-ui \
              --resource-group rg-Probuild \
              --environment managedEnvironment-rgProbuild-ae27 \
              --image probuild.azurecr.io/probuildai-ui:${{ github.sha }} \
              --cpu 0.5 \
              --memory 1Gi \
              --min-replicas 1 \
              --max-replicas 1 \
              --ingress external \
              --target-port 80 \
              --set-env-vars \
                "PORT=80" \
                "FORCE_NEW_REVISION=true" \
              --startup-probe "tcp port=8080 failure-threshold=10 interval=5 timeout=30"
          fi

